window.KAGAMI_CARDS = [
  {
    "id": 1,
    "mother": 1,
    "motherName": "生命／螺旋",
    "child": 1,
    "phase": "萌芽",
    "message": "まだ名前のないものが、あなたの内側で芽を出しています。\n\nそれは願いかもしれないし、違和感かもしれません。\n小さすぎて見落としそうな気配ほど、これからの流れを秘めています。\n\nいまは、急いで意味を与えなくても大丈夫です。",
    "title": "土の下で目覚める子",
    "sigil": "spiral",
    "hasFinalArt": false
  },
  {
    "id": 2,
    "mother": 1,
    "motherName": "生命／螺旋",
    "child": 2,
    "phase": "増勢",
    "message": "ひとつの流れが、静かに勢いを増しています。\n\n何度も思い出すこと。\nつい手を伸ばしてしまうこと。\nなぜか戻ってしまう場所。\n\nそこには、あなたの内側から自然に湧いている力があります。",
    "title": "春を飲む者",
    "sigil": "spiral",
    "hasFinalArt": false
  },
  {
    "id": 3,
    "mother": 1,
    "motherName": "生命／螺旋",
    "child": 3,
    "phase": "結合",
    "message": "あなたの中にあるものが、外の世界と触れようとしています。\n\n誰かの言葉。\n偶然の出会い。\nずっと気になっていた何か。\n\nひとつの接触が、まだ知らなかった自分を目覚めさせることがあります。",
    "title": "外の風を迎える人",
    "sigil": "spiral",
    "hasFinalArt": false
  },
  {
    "id": 4,
    "mother": 1,
    "motherName": "生命／螺旋",
    "child": 4,
    "phase": "定着",
    "message": "あなたを動かしている力が、少しずつ自分のリズムになっています。\n\n頑張らなくても戻ってくる呼吸。\n自然に満ちてくる勢い。\n以前より無理なく続く感覚。\n\n育ってきたものは、いつしか「すること」ではなく、「そう在ること」へ変わっていきます。",
    "title": "鼓動を覚えた人",
    "sigil": "spiral",
    "hasFinalArt": false
  },
  {
    "id": 5,
    "mother": 1,
    "motherName": "生命／螺旋",
    "child": 5,
    "phase": "停滞",
    "message": "内側の流れは、まだ途切れていません。\nただ今は、ひとつの方向へまとまらず、静かに揺れています。\n\n止まっているように見える時間にも、\n見えないところで何かは動き続けています。",
    "title": "水底で息を継ぐ者",
    "sigil": "spiral",
    "hasFinalArt": true
  },
  {
    "id": 6,
    "mother": 1,
    "motherName": "生命／螺旋",
    "child": 6,
    "phase": "離脱",
    "message": "今までの自分を包んでいた古い皮膚が、少しずつ合わなくなっています。\n\nかつて必要だったあり方も、今のあなたには窮屈かもしれません。\n\n離れることは、支えを失うことではなく、\nもう使わなくなった自分の形を脱いでいくことでもあります。",
    "title": "古い皮を脱ぐ者",
    "sigil": "spiral",
    "hasFinalArt": false
  },
  {
    "id": 7,
    "mother": 1,
    "motherName": "生命／螺旋",
    "child": 7,
    "phase": "変容",
    "message": "同じ形のままでは、もう先へ進めないところまで来ています。\n\n壊れていくように見えるものも、\n別の形へ移る途中なのかもしれません。\n\n以前の自分を守るより、\nまだ知らない自分に場所を空けてください。",
    "title": "二度生まれた者",
    "sigil": "spiral",
    "hasFinalArt": false
  },
  {
    "id": 8,
    "mother": 2,
    "motherName": "情愛／波紋",
    "child": 1,
    "phase": "萌芽",
    "message": "まだはっきりとは言葉にできない気持ちが、静かに生まれています。\n\n気になること。\n目で追ってしまうこと。\nふと誰かを思い出すこと。\n\nその小さな揺れは、まだ答えではなくても、確かな始まりかもしれません。",
    "title": "名を呼びかける娘",
    "sigil": "ripple",
    "hasFinalArt": false
  },
  {
    "id": 9,
    "mother": 2,
    "motherName": "情愛／波紋",
    "child": 2,
    "phase": "増勢",
    "message": "ひとつの想いが、少しずつ広がっています。\n\n考える時間が増えたり、\n以前より心が強く動いたり。\n\n無理に大きくしなくても、感情はそれ自身の速度で育っていきます。",
    "title": "灯を育てる人",
    "sigil": "ripple",
    "hasFinalArt": false
  },
  {
    "id": 10,
    "mother": 2,
    "motherName": "情愛／波紋",
    "child": 3,
    "phase": "結合",
    "message": "ひとつでは言い切れない気持ちが、あなたの中で重なり始めています。\n\n嬉しさと怖さ。\n好意と戸惑い。\n近づきたい気持ちと、守りたい距離。\n\n矛盾する感情が同時にあるとき、それらはやがて一つの想いの形をつくっていきます。",
    "title": "二つの心を抱く者",
    "sigil": "ripple",
    "hasFinalArt": false
  },
  {
    "id": 11,
    "mother": 2,
    "motherName": "情愛／波紋",
    "child": 4,
    "phase": "定着",
    "message": "何に心がほどけ、何に傷つき、何を大切にしたいのか。\n\n繰り返し感じてきたことが、少しずつあなた自身の感情の輪郭になっています。\n\n心の癖ではなく、\n「自分はこう感じる人なのだ」という静かな理解が育っています。",
    "title": "自分の井戸を知る女",
    "sigil": "ripple",
    "hasFinalArt": false
  },
  {
    "id": 12,
    "mother": 2,
    "motherName": "情愛／波紋",
    "child": 5,
    "phase": "停滞",
    "message": "心の中で、ふたつの気持ちが引き合っています。\n\n好きなのに怖い。\n離れたいのに、まだ大切。\n伝えたいのに、言葉にすると違ってしまう。\n\nどちらか一方を消さなくても、今は両方が本当なのかもしれません。",
    "title": "二つの杯を持つ人",
    "sigil": "ripple",
    "hasFinalArt": false
  },
  {
    "id": 13,
    "mother": 2,
    "motherName": "情愛／波紋",
    "child": 6,
    "phase": "離脱",
    "message": "以前ほど心が動かなくなったものがあります。\n\n嫌いになったわけでも、価値がなくなったわけでもありません。\nただ、そこに注いでいた感情が静かに戻ってきています。\n\n手放されるのは関係ではなく、\nその関係に結びついていたあなたの想いなのかもしれません。",
    "title": "手紙を海へ返す者",
    "sigil": "ripple",
    "hasFinalArt": false
  },
  {
    "id": 14,
    "mother": 2,
    "motherName": "情愛／波紋",
    "child": 7,
    "phase": "変容",
    "message": "同じ相手や出来事を前にしても、感じるものが以前とは違ってきています。\n\n恋しさが感謝へ。\n痛みが懐かしさへ。\n憧れが理解へ。\n\n気持ちは消えるだけではなく、別の温度へ変わって残ることがあります。",
    "title": "古い歌を別の声で歌う人",
    "sigil": "ripple",
    "hasFinalArt": false
  },
  {
    "id": 15,
    "mother": 3,
    "motherName": "認識／星",
    "child": 1,
    "phase": "萌芽",
    "message": "まだ言葉にならない理解が、あなたの中に灯り始めています。\n\nふと気づいたこと。\nなぜか引っかかること。\n今まで見過ごしていた小さな違和感。\n\nその光はまだ弱くても、これから何かを見分ける手がかりになるかもしれません。",
    "title": "暗がりで星を見つけた子",
    "sigil": "star",
    "hasFinalArt": false
  },
  {
    "id": 16,
    "mother": 3,
    "motherName": "認識／星",
    "child": 2,
    "phase": "増勢",
    "message": "ひとつの気づきが、少しずつ輪郭を持ち始めています。\n\n以前は偶然に見えたことが、今はつながって見えるかもしれません。\n\n理解は急に完成するのではなく、点と点が静かに結ばれていくことで深まっていきます。",
    "title": "点を結ぶ書記",
    "sigil": "star",
    "hasFinalArt": false
  },
  {
    "id": 17,
    "mother": 3,
    "motherName": "認識／星",
    "child": 3,
    "phase": "結合",
    "message": "別々に見えていたものが、ひとつの意味として結びつこうとしています。\n\n知っていたこと。\n感じていたこと。\n誰かから受け取った言葉。\n\nそれぞれの断片が重なるとき、新しい見方が生まれます。",
    "title": "破れた地図を継ぐ者",
    "sigil": "star",
    "hasFinalArt": false
  },
  {
    "id": 18,
    "mother": 3,
    "motherName": "認識／星",
    "child": 4,
    "phase": "定着",
    "message": "何度も確かめてきた理解が、あなたの中に根づき始めています。\n\nもう毎回考え直さなくても、自然に選べることが増えているかもしれません。\n\n身についた認識は、静かにものの見え方を変えていきます。",
    "title": "星図を閉じた観測者",
    "sigil": "star",
    "hasFinalArt": false
  },
  {
    "id": 19,
    "mother": 3,
    "motherName": "認識／星",
    "child": 5,
    "phase": "停滞",
    "message": "考えれば考えるほど、答えが遠のくことがあります。\n\n見えているものが多すぎて、ひとつに決められない。\nどれも間違いではないからこそ、動けない。\n\n今は無理に結論を作らず、見えているものをそのまま置いておいてもよいのかもしれません。",
    "title": "答えを棚に戻す司書",
    "sigil": "star",
    "hasFinalArt": false
  },
  {
    "id": 20,
    "mother": 3,
    "motherName": "認識／星",
    "child": 6,
    "phase": "離脱",
    "message": "これまで正しいと思っていた見方から、少しずつ距離が生まれています。\n\nそれは誤りだったということではなく、今のあなたにはもう狭くなったのかもしれません。\n\n古い理解を手放すと、そこから別の景色が見えてきます。",
    "title": "古い窓を外す者",
    "sigil": "star",
    "hasFinalArt": false
  },
  {
    "id": 21,
    "mother": 3,
    "motherName": "認識／星",
    "child": 7,
    "phase": "変容",
    "message": "ものの見え方そのものが、変わろうとしています。\n\n同じ出来事を見ても、以前とは違う意味を感じるかもしれません。\n\n理解が変わるとき、世界が変わったように見えることがあります。\nけれど変わっているのは、あなたが世界を見る位置なのかもしれません。",
    "title": "世界を逆さに見る人",
    "sigil": "star",
    "hasFinalArt": false
  },
  {
    "id": 22,
    "mother": 4,
    "motherName": "縁／結び",
    "child": 1,
    "phase": "萌芽",
    "message": "まだ名前のないつながりが、生まれ始めています。\n\n短い会話。\n偶然の重なり。\n一度きりに見える接点。\n\nその小さな結び目が、これから何かを運んでくるかもしれません。",
    "title": "名前を知らない客",
    "sigil": "knot",
    "hasFinalArt": false
  },
  {
    "id": 23,
    "mother": 4,
    "motherName": "縁／結び",
    "child": 2,
    "phase": "増勢",
    "message": "ひとつのつながりが、少しずつ強くなっています。\n\n会う回数が増える。\n言葉を交わす時間が増える。\n同じ場所へ何度も戻る。\n\n縁は、繰り返しの中で輪郭を持つことがあります。",
    "title": "同じ橋を渡る二人",
    "sigil": "knot",
    "hasFinalArt": false
  },
  {
    "id": 24,
    "mother": 4,
    "motherName": "縁／結び",
    "child": 3,
    "phase": "結合",
    "message": "別々に進んでいたものの間に、一本の線が生まれています。\n\n人と人。\n場所と出来事。\n必要としていたものと、差し出されたもの。\n\nそれぞれ単独では起こらなかった展開が、接続によって始まろうとしています。",
    "title": "糸を渡す使者",
    "sigil": "knot",
    "hasFinalArt": false
  },
  {
    "id": 25,
    "mother": 4,
    "motherName": "縁／結び",
    "child": 4,
    "phase": "定着",
    "message": "ひとつのつながりが、一時的な接点ではなくなりつつあります。\n\n会う場所。\n交わす役割。\n戻ってくる関係。\n\n気持ちの強さとは別に、\nその縁はあなたの生活の構造の中へ組み込まれ始めています。",
    "title": "鍵を預けられた客",
    "sigil": "knot",
    "hasFinalArt": false
  },
  {
    "id": 26,
    "mother": 4,
    "motherName": "縁／結び",
    "child": 5,
    "phase": "停滞",
    "message": "縁は切れていません。\nけれど、今はその先へ進むための条件が揃っていないようです。\n\n距離。\n役割。\nタイミング。\n環境。\n\nつながりそのものではなく、その間にある通路が一時的に塞がっているのかもしれません。",
    "title": "関所で待つ二人",
    "sigil": "knot",
    "hasFinalArt": false
  },
  {
    "id": 27,
    "mother": 4,
    "motherName": "縁／結び",
    "child": 6,
    "phase": "離脱",
    "message": "これまで結ばれていた線が、少しずつほどけています。\n\n会う理由がなくなる。\n役割が終わる。\n同じ場所に戻らなくなる。\n\n気持ちが残っていても、\n縁の形だけが先に変わっていくことがあります。",
    "title": "役目を終えた案内人",
    "sigil": "knot",
    "hasFinalArt": false
  },
  {
    "id": 28,
    "mother": 4,
    "motherName": "縁／結び",
    "child": 7,
    "phase": "変容",
    "message": "関係の呼び名や役割が、今までの形では収まらなくなっています。\n\n友人が仕事仲間になる。\n教える側と学ぶ側が入れ替わる。\n居場所だった場所が、思い出の場所になる。\n\n縁は続いたまま、結ばれ方だけが変わることがあります。",
    "title": "呼び名を交換する二人",
    "sigil": "knot",
    "hasFinalArt": false
  },
  {
    "id": 29,
    "mother": 5,
    "motherName": "営為／格子",
    "child": 1,
    "phase": "萌芽",
    "message": "まだ小さな行動が、日々の中に生まれています。\n\n試してみること。\n少しだけ手をつけること。\n繰り返してみたくなること。\n\nその一歩が、これからの習慣や形をつくる始まりかもしれません。",
    "title": "最初の針を刺す職人",
    "sigil": "grid",
    "hasFinalArt": false
  },
  {
    "id": 30,
    "mother": 5,
    "motherName": "営為／格子",
    "child": 2,
    "phase": "増勢",
    "message": "続けてきた行動に、少しずつ勢いが生まれています。\n\n回数が増える。\n手順がわかってくる。\n迷う時間が減っていく。\n\n積み重ねは、気づかないうちにあなたの力になっています。",
    "title": "手を止めない織り手",
    "sigil": "grid",
    "hasFinalArt": false
  },
  {
    "id": 31,
    "mother": 5,
    "motherName": "営為／格子",
    "child": 3,
    "phase": "結合",
    "message": "別々にしていたことが、ひとつの流れとしてつながり始めています。\n\n経験と技術。\n時間と場所。\n準備と実行。\n\n組み合わさることで、今までより自然に進める形が見えてくるかもしれません。",
    "title": "道具を組み替える工匠",
    "sigil": "grid",
    "hasFinalArt": false
  },
  {
    "id": 32,
    "mother": 5,
    "motherName": "営為／格子",
    "child": 4,
    "phase": "定着",
    "message": "繰り返してきたことが、あなたの中に手順として残っています。\n\n考えなくてもできること。\n自然に始められること。\n\n積み重ねてきた営みは、静かにあなたを支える土台になっています。",
    "title": "目を閉じても編める人",
    "sigil": "grid",
    "hasFinalArt": false
  },
  {
    "id": 33,
    "mother": 5,
    "motherName": "営為／格子",
    "child": 5,
    "phase": "停滞",
    "message": "手を動かしているのに、前へ進んでいる感じがしないことがあります。\n\n同じところを直す。\n始めては止まる。\nやることばかり増えていく。\n\n今は作業を増やすより、どこで詰まっているのかを見る方がよいのかもしれません。",
    "title": "同じ石を磨き続ける職人",
    "sigil": "grid",
    "hasFinalArt": false
  },
  {
    "id": 34,
    "mother": 5,
    "motherName": "営為／格子",
    "child": 6,
    "phase": "離脱",
    "message": "続けてきたやり方から、少しずつ距離が生まれています。\n\n以前は必要だった手順も、今は重く感じることがあります。\n\nやめることは失敗ではなく、今の自分に合う形へ移る準備になることがあります。",
    "title": "古い道具を置く人",
    "sigil": "grid",
    "hasFinalArt": false
  },
  {
    "id": 35,
    "mother": 5,
    "motherName": "営為／格子",
    "child": 7,
    "phase": "変容",
    "message": "これまでのやり方では、もう同じ成果にたどり着けないのかもしれません。\n\n手順を変える。\n役割を変える。\n続け方そのものを組み替える。\n\n営みの形が変わるとき、新しい力の使い方が見えてきます。",
    "title": "工房を建て替える者",
    "sigil": "grid",
    "hasFinalArt": false
  },
  {
    "id": 36,
    "mother": 6,
    "motherName": "基盤／印章",
    "child": 1,
    "phase": "萌芽",
    "message": "まだ小さな安心が、あなたの足元に生まれています。\n\nひと息つける場所。\n戻りたくなる時間。\n無理をしなくてよい感覚。\n\nその小さな安定が、これからの支えになるかもしれません。",
    "title": "小さな火を囲う人",
    "sigil": "seal",
    "hasFinalArt": false
  },
  {
    "id": 37,
    "mother": 6,
    "motherName": "基盤／印章",
    "child": 2,
    "phase": "増勢",
    "message": "支えになるものが、少しずつ増えています。\n\n頼れる場所。\n続けられる習慣。\n安心して戻れる関係。\n\nひとつひとつは小さくても、重なればあなたを守る厚みになります。",
    "title": "柱を増やす大工",
    "sigil": "seal",
    "hasFinalArt": false
  },
  {
    "id": 38,
    "mother": 6,
    "motherName": "基盤／印章",
    "child": 3,
    "phase": "結合",
    "message": "別々だった支えが、ひとつにつながろうとしています。\n\n生活と気持ち。\n身体と時間。\n人と場所。\n\nそれぞれが噛み合うことで、今までより安定した足場が生まれるかもしれません。",
    "title": "梁を渡す者",
    "sigil": "seal",
    "hasFinalArt": false
  },
  {
    "id": 39,
    "mother": 6,
    "motherName": "基盤／印章",
    "child": 4,
    "phase": "定着",
    "message": "あなたを支えるものが、しっかりと根を下ろしています。\n\n意識しなくても守られていること。\n自然に戻れる場所。\n\n基盤は目立たなくても、あなたが動くたびにその下で支え続けています。",
    "title": "家の印を守る女",
    "sigil": "seal",
    "hasFinalArt": false
  },
  {
    "id": 40,
    "mother": 6,
    "motherName": "基盤／印章",
    "child": 5,
    "phase": "停滞",
    "message": "足元を固めようとするほど、動けなくなることがあります。\n\n崩れたくない。\n失いたくない。\n間違えたくない。\n\n守ることが強くなりすぎるとき、安定はいつの間にか停止へ変わることがあります。",
    "title": "門を閉じすぎた番人",
    "sigil": "seal",
    "hasFinalArt": false
  },
  {
    "id": 41,
    "mother": 6,
    "motherName": "基盤／印章",
    "child": 6,
    "phase": "離脱",
    "message": "これまであなたを支えていたものから、少しずつ離れる時が来ています。\n\n安心だった場所。\n慣れた仕組み。\n昔の自分を守っていた形。\n\n支えを手放すことは不安でも、新しい足場を作るための余白になります。",
    "title": "故郷の鍵を返す者",
    "sigil": "seal",
    "hasFinalArt": false
  },
  {
    "id": 42,
    "mother": 6,
    "motherName": "基盤／印章",
    "child": 7,
    "phase": "変容",
    "message": "あなたの足元そのものが、組み替わろうとしています。\n\n以前なら安心できたものが、今はもう十分ではないかもしれません。\n\n新しい基盤は、古い形を守ることではなく、今の自分に合う支えを選び直すところから始まります。",
    "title": "土台を掘り直す人",
    "sigil": "seal",
    "hasFinalArt": false
  },
  {
    "id": 43,
    "mother": 7,
    "motherName": "道／欠環",
    "child": 1,
    "phase": "萌芽",
    "message": "まだ細い道が、あなたの前に現れ始めています。\n\nはっきりした目的地は見えなくても、なぜか気になる方向があります。\n\n最初の一歩は、答えを知っているからではなく、少しだけ惹かれる方へ向かうことから始まります。",
    "title": "地図にない道を指す子",
    "sigil": "broken-ring",
    "hasFinalArt": false
  },
  {
    "id": 44,
    "mother": 7,
    "motherName": "道／欠環",
    "child": 2,
    "phase": "増勢",
    "message": "進み始めた道が、少しずつあなたを遠くへ運んでいます。\n\n選んだこと。\n続けていること。\n何度も戻る方向。\n\n小さな選択の積み重ねが、いつの間にかひとつの流れになっています。",
    "title": "遠ざかる灯を追う旅人",
    "sigil": "broken-ring",
    "hasFinalArt": false
  },
  {
    "id": 45,
    "mother": 7,
    "motherName": "道／欠環",
    "child": 3,
    "phase": "結合",
    "message": "いくつかの道が、ひとつの場所で交わろうとしています。\n\nこれまで別々だと思っていた経験が、今の選択につながっているのかもしれません。\n\n遠回りに見えた道も、ここへ来るための一部だった可能性があります。",
    "title": "十字路で出会う者たち",
    "sigil": "broken-ring",
    "hasFinalArt": false
  },
  {
    "id": 46,
    "mother": 7,
    "motherName": "道／欠環",
    "child": 4,
    "phase": "定着",
    "message": "歩き続けてきた道が、あなたの中でひとつの軸になっています。\n\n迷っても戻れる方向。\n自然に選びやすい道。\n\nそれは正解というより、今のあなたが何度も選んできた軌跡です。",
    "title": "帰る方角を知る旅人",
    "sigil": "broken-ring",
    "hasFinalArt": false
  },
  {
    "id": 47,
    "mother": 7,
    "motherName": "道／欠環",
    "child": 5,
    "phase": "停滞",
    "message": "進みたいのに、どの道を選べばよいのかわからないことがあります。\n\n戻るべきか。\n進むべきか。\n別の道を探すべきか。\n\n立ち止まる時間も、道の一部です。\n今はまだ、方向を決めないという選択もあります。",
    "title": "分かれ道に座る人",
    "sigil": "broken-ring",
    "hasFinalArt": false
  },
  {
    "id": 48,
    "mother": 7,
    "motherName": "道／欠環",
    "child": 6,
    "phase": "離脱",
    "message": "これまで歩いてきた道から、少しずつ外れようとしています。\n\n間違っていたからではなく、もう同じ方向へ進み続ける必要がなくなったのかもしれません。\n\n道を離れることは、迷うことではなく、新しい方向を探す余白でもあります。",
    "title": "街道を降りる旅人",
    "sigil": "broken-ring",
    "hasFinalArt": false
  },
  {
    "id": 49,
    "mother": 7,
    "motherName": "道／欠環",
    "child": 7,
    "phase": "変容",
    "message": "道そのものが、あなたの前で形を変えようとしています。\n\nこれまで目指していた場所が、もう同じ意味を持たないことがあります。\n\n目的地を変える。\n歩き方を変える。\nあるいは、道を探すこと自体をやめる。\n\nこれまでの旅を否定せずに、次の方向へ移ってもよいのです。",
    "title": "目的地の名を消す巡礼者",
    "sigil": "broken-ring",
    "hasFinalArt": false
  }
];
